apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-sample-catapp-pipeline
spec:
  params:
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: tekton-sample-catapp:latest
  resources:
    - name: source
      type: git
  tasks:
    - name: build-task
      taskRef:
        name: build-docker
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      resources:
        inputs:
          - name: source
            resource: source
    - name: deploy-task
      runAfter: [build-task]
      taskRef:
        name: deploy-kubectl
      resources:
        inputs:
          - name: source
            resource: source
