apiVersion: apps/v1
kind: Deployment
metadata:
  name: ups216-tekton-sample-catapp
  labels:
    app: ups216-tekton-sample-catapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ups216-tekton-sample-catapp
  template:
    metadata:
      labels:
        app: ups216-tekton-sample-catapp
    spec:
      containers:
        - name: ups216-tekton-sample-catapp
          image: ups216-tekton-sample-catapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
